POST http://localhost:7071/api/HttpTrigger
Accept: application/json, text/plain, */*
Referer: http://localhost:8080/oidc-callback
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlY3NVVtVkRqNHpJblBsZ0R6eHI1NCJ9.eyJpc3MiOiJodHRwczovL3NvbG91cC5hdS5hdXRoMC5jb20vIiwic3ViIjoiYXV0aDB8NWVlMjIwMjJhYWRkOTYwMDE5MzAxNDY2IiwiYXVkIjpbImh0dHBzOi8vc29sb3VwLmFwcC9hcGkiLCJodHRwczovL3NvbG91cC5hdS5hdXRoMC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNTk2ODAyNzk4LCJleHAiOjE1OTY4MDk5OTgsImF6cCI6InlKUWNYSnZuWmNJZTYySzA2QzV3WE1yT0RmT1BobkZGIiwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBlbWFpbCJ9.fpvwhYfQbAquXkLfe89jh0bU3vkqa9wMKHJGZMjc_b4vnZKqMMn8FNbzpUhODNGddZoo3jxxrAfSaYQZ5TUBZHi0JsGNtJWGBXDP1t9Ag5UF6yIy2bioov6GvmFv_t-7CHq4Wtq0Jo3oi_XeFU4c5gLCP3rHWNpA8hRxeSe2wYaND7aeMoM2FrRpW9Wzu7_VavLnZYOo5Bcmu1_3bsUqaRtcJcWm0htI46miD0lXSvw-mj7GaYyFU5gk2xZ5RMo5ah2Rs95ZP0NT-t1sgv5saTazP5AYbrbhD6fPMpNXV_KrTer6_5_BvwzXI97mXFVSLsPf8uM9DfrUA_M9WaMu4Q