POST http://localhost:7071/api/HttpTrigger
Accept: application/json, text/plain, */*
Referer: http://localhost:8080/oidc-callback
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36
authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlY3NVVtVkRqNHpJblBsZ0R6eHI1NCJ9.eyJpc3MiOiJodHRwczovL3NvbG91cC5hdS5hdXRoMC5jb20vIiwic3ViIjoiYXV0aDB8NWVlMjIwMjJhYWRkOTYwMDE5MzAxNDY2IiwiYXVkIjpbImh0dHBzOi8vc29sb3VwLmFwcC9hcGkiLCJodHRwczovL3NvbG91cC5hdS5hdXRoMC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNTk2NjI4Mjc4LCJleHAiOjE1OTY2MzU0NzgsImF6cCI6InlKUWNYSnZuWmNJZTYySzA2QzV3WE1yT0RmT1BobkZGIiwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBlbWFpbCJ9.eyKX3NCvWmGzjdi_174Ar1T1jWAuXtP6EAmoCnA3Ye568KuSes-ll9lwJxNVXW7iWvNlAXf3dfkbByf9U1_tj7xitdbJXoMVF7ZarFvZI30boYOJCKJfTwbDc-tgwQfKWyoLYXNxtH8IYhr7BgiX0n1js7W0fxZFACATrMDX3SNhN5FS70T4WTsX3_nMVfU2D2AS5peTwRIqpUTzse-rMus_9rBIWw2t5IHE4_jEqIVHEfCtW6R7yWIWLEd1SGslI9QVWh1AMY2p2S6QzAxkYBhI4pzm8lJpeCFBDlOsJE0LhCKWe_yrYB1ojlUh_XAnm59W5DvrNShDltvl2x2PlA